git:
  depth: 3

language: python

python:
  - "3.9"

addons:
  apt:
    packages:
      - cflow
      - graphviz

install:
  - pip install --upgrade pip setuptools
  # pycflow2dot
  - pip install .

script:
  - cd tests/
  - make all
